deployment/urls.py
"""
Deployment Management
This program is designed to deploy Django code to remote locations
Copyright (C) 2015  James Fourman

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from django.conf.urls import patterns, include, url
from . import views


urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^new_deployment/$', views.new_deployment, name='new_deployment'),
    url(r'^run_deployments/$', views.run_deployments, name='run_deployments'),
    url(r'^(?P<deployment_id>\d+)/$', views.get_deployment, name='get_deployment'),
)

django_deployment/urls.py
"""
Deployment Management
This program is designed to deploy Django code to remote locations
Copyright (C) 2015  James Fourman

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^', include('deployment.urls', namespace='deployment')),
    url(r'^admin/', include(admin.site.urls)),
)

deployment/models.py
"""
Deployment Management
This program is designed to deploy Django code to remote locations
Copyright (C) 2015  James Fourman

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from django.db import models
from django.contrib.auth.models import User
from .validators import validate_file_extension


class Server(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)


class Status(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'Status'

    def __str__(self):
        return self.name


class DeploymentType(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Deployment(models.Model):
    name = models.CharField(max_length=200)
    deployment_file = models.FileField(null=True, blank=True, upload_to='deployment_files', validators=[validate_file_extension])
    status = models.ForeignKey(Status, editable=False)
    requester = models.ForeignKey(User, related_name='requester')
    creator = models.ForeignKey(User, related_name='creator', editable=False)
    requested_date = models.DateTimeField(auto_now_add=True)
    create_date = models.DateTimeField(auto_now_add=True)
    deployment_type = models.ForeignKey(DeploymentType)

    def __str__(self):
        return self.name


class DeploymentStep(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class DeploymentLog(models.Model):
    deployment = models.ForeignKey(Deployment)
    timestamp = models.DateTimeField(auto_now=True)
    log_information = models.TextField()
    source_system = models.CharField(max_length=200, null=True)
    deployment_step = models.ForeignKey(DeploymentStep)

    def __str__(self):
        return self.deployment.name


class DeploymentConfiguration(models.Model):
    deployment = models.ForeignKey(Deployment)
    configuration_type = models.ForeignKey(DeploymentType)
    order_num = models.IntegerField()
    script_file = models.FileField()

    class Meta:
        unique_together = ('deployment', 'configuration_type')

    def __str__(self):
        return self.deployment


class SettingType(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Setting(models.Model):
    deployment_type = models.ForeignKey(DeploymentType)
    setting_type = models.ForeignKey(SettingType)
    value = models.CharField(max_length=200)

    def __str__(self):
        return self.name + ':' + self.value

deployment/forms.py
"""
Deployment Management
This program is designed to deploy Django code to remote locations
Copyright (C) 2015  James Fourman

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from django.forms import ModelForm
from .models import Deployment


class DeploymentForm(ModelForm):
    class Meta:
        model = Deployment
        fields = ['name', 'deployment_file', 'status', 'requester', 'creator', 'requested_date', 'create_date', 'deployment_type']

deployment/views.py
"""
Deployment Management
This program is designed to deploy Django code to remote locations
Copyright (C) 2015  James Fourman

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
import zipfile
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from .models import Deployment, Status, DeploymentLog, DeploymentStep
from .forms import DeploymentForm


def index(request):
    queued = Deployment.objects.filter(status__name="queued")

    active = Deployment.objects.filter(status__name="active")
    success = Deployment.objects.filter(status__name="success")
    failed = Deployment.objects.filter(status__name="failed")

    params = {
        'queued': queued,
        'active': active,
        'success': success,
        'failed': failed
    }
    return render(request, "deployment/index.html", params)


def new_deployment(request):
    if request.method == 'POST':
        form = DeploymentForm(request.POST, request.FILES)
        if form.is_valid():
            deployment = form.save(commit=False)
            deployment.creator = request.user
            deployment.status = Status.objects.get(pk=1)
            deployment.save()
            deployment_log = DeploymentLog()
            deployment_log.deployment = deployment
            deployment_log.log_information = "Deployment has been created"
            deployment_log.source_system = "DeplomentManagement"
            deployment_log.deployment_step = DeploymentStep.objects.get(pk=1)
            deployment_log.save()
            return HttpResponseRedirect(reverse('deployment:index'))
    else:
        form = DeploymentForm({'requester': request.user})

    params = {
        'form': form
    }
    return render(request, "deployment/new_deployment.html", params)


def get_deployment(request, deployment_id):
    deployment = Deployment.objects.get(pk=deployment_id)
    deployment_logs = DeploymentLog.objects.filter(deployment_id=deployment_id)
    params = {
        'deployment': deployment,
        'deployment_logs': deployment_logs
    }
    return render(request, "deployment/get_deployment.html", params)


def run_deployments(request):
    queued = Deployment.objects.filter(status__name="queued")
    for deployment in queued:
        extension = deployment.deployment_file.name.split(".")[-1]
        name = deployment.deployment_file.name.split("/")[-1].split(".")[0]
        if extension == "zip":
            print "Running unzip on %s" % (name)
            with zipfile.ZipFile(deployment.deployment_file.path) as zf:
                zf.extractall("C:\\Users\\zerocool\\Documents\\Git\\django_deployment\\test\\" + name)
        elif extension == "tar":
            print "Running untar"
        elif extension == "gz":
            print "Running gz"

        # deployment.status = 2
        # deployment.save()

    return render(request, "deployment/deployment_started.html")

deployment/templates/deployment/deployment_started.html
{% extends "base.html" %}
{% block content %}
Deployments have started
{% endblock content %}

deployment/templates/deployment/get_deployment.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-6">			
			<div class="container">
				<div class="row">
					<div class="col-md-2"><strong>Name:</strong></div>
					<div class="col-md-2">{{ deployment.name }}</div>
				</div>
				<div class="row">
					<div class="col-md-2"><strong>Deployment File:</strong></div>
					<div class="col-md-2">{% if deployment.deployment_file %}{{ deployment.deployment_file }}{% else %}No File Available{% endif %}</div>
				</div>
				<div class="row">
					<div class="col-md-2"><strong>Status:</strong></div>
					<div class="col-md-2">{{ deployment.status }}</div>
				</div>
				<div class="row">
					<div class="col-md-2"><strong>Requester:</strong></div>
					<div class="col-md-2">{{ deployment.requester.last_name }}, {{ deployment.requester.first_name }}</div>
				</div>
				<div class="row">
					<div class="col-md-2"><strong>Requested Date:</strong></div>
					<div class="col-md-2">{{ deployment.requested_date }}</div>
				</div>
				<div class="row">
					<div class="col-md-2"><strong>Creator:</strong></div>
					<div class="col-md-2">{{ deployment.creator.last_name }}, {{ deployment.creator.first_name }}</div>
				</div>
				<div class="row">
					<div class="col-md-2"><strong>Create Date:</strong></div>
					<div class="col-md-2">{{ deployment.create_date }}</div>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			{% for deployment_log in deployment_logs %}
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						{{ deployment_log.log_information }}
					</div>	
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</div>
{% endblock content %}

deployment/templates/deployment/index.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<h1>Deployments</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<a class="btn btn-default btn-primary" href="{% url 'deployment:new_deployment' %}">Create New Deployment</a>
		</div>
	</div>
	{% if queued %}
	<div class="row">
		<div class="col-md-12">
			<h2>Queued</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3">
			<strong>Name</strong>
		</div>
		<div class="col-md-3">
			<strong>Requester</strong>
		</div>
		<div class="col-md-3">
			<strong>Requested Date</strong>
		</div>
		<div class="col-md-3">
			<strong>Deployment Type</strong>
		</div>
	</div>
	{% for items in queued %}
	<div class="row">
		<div class="col-md-3">
			<a href="{% url 'deployment:get_deployment' items.id %}">{{ items.name }}</a>
		</div>
		<div class="col-md-3">
			{% if items.requester %}
			{{ items.requester.last_name }}, {{ items.requester.first_name }}
			{% endif %}
		</div>
		<div class="col-md-3">
			{{ items.requested_date }}
		</div>
		<div class="col-md-3">
			{{ items.deployment_type }}
		</div>
	</div>
	{% endfor %}
	{% endif %}

	{% if active %}
	<div class="row">
		<div class="col-md-12">
			<h2>Active</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3">
			<strong>Name</strong>
		</div>
		<div class="col-md-3">
			<strong>Requester</strong>
		</div>
		<div class="col-md-3">
			<strong>Requested Date</strong>
		</div>
		<div class="col-md-3">
			<strong>Deployment Type</strong>
		</div>
	</div>
	{% for items in Active %}
	<div class="row">
		<div class="col-md-3">
			{{ items.name }}
		</div>
		<div class="col-md-3">
			{% if items.requester %}
			{{ items.requester.last_name }}, {{ items.requester.first_name }}
			{% endif %}
		</div>
		<div class="col-md-3">
			{{ items.requested_date }}
		</div>
		<div class="col-md-3">
			{{ items.deployment_type }}
		</div>
	</div>
	{% endfor %}
	{% endif %}

	{% if failed %}
	<div class="row">
		<div class="col-md-12">
			<h2>Failed</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3">
			<strong>Name</strong>
		</div>
		<div class="col-md-3">
			<strong>Requester</strong>
		</div>
		<div class="col-md-3">
			<strong>Requested Date</strong>
		</div>
		<div class="col-md-3">
			<strong>Deployment Type</strong>
		</div>
	</div>
	{% for items in failed %}
	<div class="row">
		<div class="col-md-3">
			{{ items.name }}
		</div>
		<div class="col-md-3">
			{% if items.requester %}
			{{ items.requester.last_name }}, {{ items.requester.first_name }}
			{% endif %}
		</div>
		<div class="col-md-3">
			{{ items.requested_date }}
		</div>
		<div class="col-md-3">
			{{ items.deployment_type }}
		</div>
	</div>
	{% endfor %}
	{% endif %}

	{% if success %}
	<div class="row">
		<div class="col-md-12">
			<h2>Success</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3">
			<strong>Name</strong>
		</div>
		<div class="col-md-3">
			<strong>Requester</strong>
		</div>
		<div class="col-md-3">
			<strong>Requested Date</strong>
		</div>
		<div class="col-md-3">
			<strong>Deployment Type</strong>
		</div>
	</div>
	{% for items in success %}
	<div class="row">
		<div class="col-md-3">
			{{ items.name }}
		</div>
		<div class="col-md-3">
			{% if items.requester %}
			{{ items.requester.last_name }}, {{ items.requester.first_name }}
			{% endif %}
		</div>
		<div class="col-md-3">
			{{ items.requested_date }}
		</div>
		<div class="col-md-3">
			{{ items.deployment_type }}
		</div>
	</div>
	{% endfor %}
	{% endif %}
</div>
{% endblock content %}

deployment/templates/deployment/new_deployment.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load breadcrumbs %}
{% block breadcrumbs %}
	<li>{% breadcrumb_url 'New Deployment' 'deployment:new_deployment' %}</li>
{% endblock breadcrumbs %}
{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<h1>New Deployment</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<form action="" method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{% for field in form %}
				<div class="form-group">
					{{ field.label_tag }}
					{{ field|add_class:"form-control" }}					
				</div>
				{% if field.errors %}
				<div class="alert alert-danger">
					{{ field.errors|striptags }}
				</div>
				{% endif %}
				{% endfor %}					
			</table>
			<div>	
				<br/>
				<button type="submit" class="btn btn-primary">Submit</button>&nbsp;
				<button type="Reset" class="btn btn-primary">Reset</button>&nbsp;
				<a href="{% url 'deployment:index' %}" class="btn btn-primary">Back </a>
			</div>
		</form>
	</div>
</div>
</div>
{% endblock %}