deployment/urls.py
"""
Deployment Management
This program is designed to deploy Django code to remote locations
Copyright (C) 2015  James Fourman

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from django.conf.urls import patterns, include, url
from . import views


urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^new_deployment/$', views.new_deployment, name='new_deployment'),
    url(r'^run_deployments/$', views.run_deployments, name='run_deployments'),
    url(r'^(?P<deployment_id>\d+)/$', views.get_deployment, name='get_deployment'),
)

django_deployment/urls.py
"""
Deployment Management
This program is designed to deploy Django code to remote locations
Copyright (C) 2015  James Fourman

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^', include('deployment.urls', namespace='deployment')),
    url(r'^admin/', include(admin.site.urls)),
)

templates/base.html
{% load breadcrumbs %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Deployment Management</title>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
	{% block styles %}
	{% endblock styles %}
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header"><a href="" class="navbar-brand">Deployment Management</a></div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li class=""><a href="{% url 'deployment:index' %}">Deployments</a></li>
					<li><a href="{% url 'deployment:run_deployments' %}">Run Deployments</a></li>
				</ul>
			</div>
		</div>
	</nav>

	<div>
		<ol class="breadcrumb">
			<li>{% breadcrumb_url 'Home' 'deployment:index' %}</li>
			{% block breadcrumbs %}
			{% endblock breadcrumbs %}
		</ol>
	</div>

	{% block content %}
	
	{% endblock content %}
	<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	{% block scripts %}
	{% endblock scripts %}
</body>
</html>